import { Navbar } from './components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { ThemeProvider } from './context/ThemeContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Gita Learn',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="en" data-theme="light">     
      <body className={inter.className}>
     
      <ThemeProvider>
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
      
    </html>
  )
}
